[package]
name = "multi_waka"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny_http = "0.12"
ureq = { version = "2.9", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21"
dotenvy = "0.15.7"
chrono = "0.4.43"
